version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Dhaka'
    labels:
      - 'dependencies'
      - 'npm'
    versioning-strategy: increase
    open-pull-requests-limit: 10
    groups:
      production-deps:
        dependency-type: 'production'
        update-types:
          - 'patch'
          - 'minor'
      dev-deps:
        dependency-type: 'development'
        update-types:
          - 'patch'
          - 'minor'

  - package-ecosystem: 'docker'
    directory: '/backend/docker'
    schedule:
      interval: 'monthly'
    labels:
      - 'dependencies'
      - 'docker'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - 'dependencies'
      - 'github-actions'
